export const light = {
  backgroundColors: {
    mainColor: '#F9FAFF',
    headerColor: '#32394A',
    orangeColor: '#ff6b00',
    blueColor: '#00b2ff',
    lineColor: '#E4E8EF',
    modalColor: '#fff',
    btnAddColor: 'rgba(163, 228, 255, 40%)',
  },
  fontFamily: {
    mainFontFamily: 'Montserrat',
    secondaryFontFamily: 'Montserrat Alternates',
  },
  textColors: {
    sidebarColor: '#606060',
    popupColor: '#2E2E2E',
    popupBtnColor: '#606060',
    cardTitleColor: '#09244b',
    ratingTitleColor: '#000',
    numberActiveColor: '#000',
    detailsTitleColor: '#000',
    numberColor: '#787878',
    arrowColor: '#393939',
    genreColor: '#09244b',
    menuTitleColor: '#09244b',
    genreListColor: '#2e2e2e',
    iconColor: '#A3E4FF',
    activeIconColor: '#A3E4FF',
    addPlusColor: '#fff',
    searchColor: '#829BB0',
    modalColorTitle: '#343434',
    modalColorPlaceholder: '#828282',
  },
};

export const dark = {
  backgroundColors: {
    mainColor: '#202128',
    headerColor: 'pink',
    orangeColor: '#ff6b00',
    blueColor: '#ff6b00',
    lineColor: '#424A50',
    modalColor: '#fff',
    btnAddColor: 'rgba(50, 54, 55, 45%)',
  },
  fontFamily: {
    mainFontFamily: 'Montserrat',
    secondaryFontFamily: 'Montserrat Alternates',
  },
  textColors: {
    sidebarColor: '#424A50',
    popupColor: '#2E2E2E',
    popupBtnColor: '#A42E27',
    genreColor: '#A42E27',
    cardTitleColor: '#fafafa',
    ratingTitleColor: '#fafafa',
    genreListColor: '#fafafa',
    detailsTitleColor: '#fafafa',
    menuTitleColor: '#A42E27',
    numberColor: '#bcbcbc',
    arrowColor: '#aaa6a6',
    numberActiveColor: '#fafafa',
    iconColor: '#424A50',
    activeIconColor: '#A42E27',
    addPlusColor: '#5f5f5f',
    searchColor: '#424A50',
    modalColorTitle: 'pink',
    modalColorPlaceholder: 'pink',
  },
};
