export const MOVIE_TYPES_PREFIX = {
  setMoviesAction: 'movie/setMoviesAction',
  setMoviesScrollAction: 'movie/setMoviesScrollAction',
  setMoviesGenreAction: 'movie/setMovieGenreAction',
  setMoviesScrollGenreAction: 'movie/setMoviesScrollGenreAction',
  setSearchMovieAction: 'movie/setSearchMovieAction',
  setSearchScrollMovieAction: 'movie/setSearchScrollMovieAction',
  addCommentAction: 'movie/addCommentAction',
  getCommentsAction: 'movie/getCommentsAction',
  getFavoriteMovieAction: 'movie/getFavoriteMovieAction',
  getWatchLaterMovieAction: 'movie/getWatchLaterMovieAction',
  addMovieToFavoriteAction: 'movie/addMovieToFavoriteAction',
  removeMovieFromFavoriteAction: 'movie/removeMovieFromFavoriteAction',
  addMovieToWatchLaterAction: 'movie/addMovieToWatchLaterAction',
  removeMovieFromWatchLaterAction: 'movie/removeMovieFromWatchLaterAction',
};
